export type Layover = {
  m45: string;
  m90: string;
  m180: string;
};

export type Airport = {
  icao: string;
  iata: string;
  name: string;
  city: string;
  country: string;
  lat: number;
  lon: number;
  tz: string;
  elevationFt: number;
  oneLiner: string;
  terminals: string;
  security: string;
  connection: string;
  watch: string;
  skyline: string;
  layover: Layover;
  heavies: string;
};

export const AIRPORTS: Airport[] = [
  {
    icao: "KORD",
    iata: "ORD",
    name: "O'Hare",
    city: "Chicago",
    country: "US",
    lat: 41.9786,
    lon: -87.9048,
    tz: "America/Chicago",
    elevationFt: 672,
    oneLiner: "United’s fortress, American’s other hub, and the best widebody mix in the Midwest.",
    terminals: "T1 United, T2 mixed, T3 American, T5 international.",
    security: "PreCheck in every terminal. International arrivals land in T5 and reclear customs there.",
    connection: "T1–T2–T3 are airside. T5 is not — budget 25–40 min plus the ATS or a reclear if you arrive internationally.",
    watch: "T5 food court and gate windows face the international ramp. T1 rotunda looks over United’s widebody gates. Heavies: BA, LH, JL, NH, EK, QR, TK, LX.",
    skyline: "Downtown sits southeast of the field. Eastbound departures often put the skyline off the right; southbound, off the left.",
    layover: {
      m45: "Stay in your departure terminal. Don’t change buildings.",
      m90: "Eat in-terminal. T3 and T1 have the most options. Skip the city.",
      m180: "T1–T3 are walkable airside. A city run is only realistic if you have bags-in-hold and three hours plus, and even then it’s tight.",
    },
    heavies: "BA, LH, LX, OS, SK, QR, EK, TK, NH, JL, EY, SQ",
  },
  {
    icao: "KMDW",
    iata: "MDW",
    name: "Midway",
    city: "Chicago",
    country: "US",
    lat: 41.7868,
    lon: -87.7522,
    tz: "America/Chicago",
    elevationFt: 620,
    oneLiner: "Close-in Southwest field. Short runways, loud departures, downtown on a short final.",
    terminals: "One main terminal, three concourses A–C.",
    security: "A single checkpoint. PreCheck is there but the line is the line — Midway is compact.",
    connection: "Everything is one building. A 35-minute connection is normal here.",
    watch: "Concourse A windows look over the south ramp. Nothing widebody — this is 737 country.",
    skyline: "Arrivals from the east can run the lakefront. Sit on the right on a typical 31C final for downtown.",
    layover: {
      m45: "You’re already at the gate. Grab food in the food court past security.",
      m90: "Stay airside. The city is close in miles, not in time.",
      m180: "You can make a neighborhood meal in Bridgeport or Pilsen if you have no checked bag. Tight.",
    },
    heavies: "Rare. Occasional diversion widebodies.",
  },
  {
    icao: "KJFK",
    iata: "JFK",
    name: "Kennedy",
    city: "New York",
    country: "US",
    lat: 40.6413,
    lon: -73.7781,
    tz: "America/New_York",
    elevationFt: 13,
    oneLiner: "The US international gateway. Terminals are separate worlds — treat a terminal change as a new airport.",
    terminals: "T1, T4, T5 (JetBlue), T7, T8 (American). T2 is gone.",
    security: "Each terminal has its own checkpoint. AirTrain is landside. PreCheck availability varies by terminal.",
    connection: "Different terminals usually means AirTrain + re-security. Self-connects under 2 hours are a gamble.",
    watch: "T4 terrace-facing gates catch heavies. T5 has good ramp glass. T8 for AA long-haul.",
    skyline: "Manhattan is west-northwest. On a 31L departure you often see it off the right after the turn.",
    layover: {
      m45: "Do not change terminals.",
      m90: "Stay inside your terminal. T4 and T5 have enough food to survive.",
      m180: "A terminal change is possible. A city run is not, unless you like watching the clock the whole time.",
    },
    heavies: "EK, QR, EY, BA, VS, AF, DL, AA, SQ, EK, KE, NH, JL",
  },
  {
    icao: "KLAX",
    iata: "LAX",
    name: "Los Angeles",
    city: "Los Angeles",
    country: "US",
    lat: 33.9416,
    lon: -118.4085,
    tz: "America/Los_Angeles",
    elevationFt: 128,
    oneLiner: "West-coast long-haul factory. Ocean departures, Tom Bradley heavies, and a horseshoe that takes longer than it looks.",
    terminals: "TBIT (TBIT/T3/T4/T5/T6/T7/T8) plus T1. TBIT is the international core.",
    security: "PreCheck in most terminals. TBIT can be slow in the evening bank.",
    connection: "The north and south complexes are connected airside via tunnels and the new walkways — still budget 20–30 min of walking.",
    watch: "TBIT gates for A380s and Gulf heavies. Inboard TBIT windows look at the Bradley alley.",
    skyline: "Ocean is west. On a 25 departure you see water off the nose; downtown is east, often behind you.",
    layover: {
      m45: "Stay put. The horseshoe eats time.",
      m90: "Eat in your terminal. TBIT has the best airside food.",
      m180: "You can walk TBIT to T4/T5. The city is a trap on a three-hour sit.",
    },
    heavies: "SQ, NH, JL, KE, QF, EK, QR, BA, AF, NZ, VA",
  },
  {
    icao: "KSFO",
    iata: "SFO",
    name: "San Francisco",
    city: "San Francisco",
    country: "US",
    lat: 37.6213,
    lon: -122.379,
    tz: "America/Los_Angeles",
    elevationFt: 13,
    oneLiner: "Fog, long-haul, and a bay that makes every approach a view. United’s west hub.",
    terminals: "T1, T2, T3 (United), International G.",
    security: "PreCheck in every terminal. International G has its own checkpoint.",
    connection: "Domestic terminals are airside-linked. G to domestic can require a walk plus possible reclear on arrival.",
    watch: "G gates for heavies over the bay. T3 also sees United 787s and 777s.",
    skyline: "The city and bridge sit north of the field. On a 28 departure the bay is off the right almost immediately.",
    layover: {
      m45: "Stay in terminal.",
      m90: "Airside food is fine. Don’t leave security.",
      m180: "BART to the city is possible with no bag, but 90 minutes downtown is the real budget — most people overstay.",
    },
    heavies: "UA, SQ, NH, JL, EK, BA, LH, AF, QF, NZ, PR",
  },
  {
    icao: "KSEA",
    iata: "SEA",
    name: "Sea-Tac",
    city: "Seattle",
    country: "US",
    lat: 47.4502,
    lon: -122.3088,
    tz: "America/Los_Angeles",
    elevationFt: 433,
    oneLiner: "Alaska’s home and a widebody launchpad to Asia. Rain, volcanoes, and a single long terminal.",
    terminals: "One main terminal, A–D plus N and S satellites.",
    security: "A central checkpoint plus satellite checkpoints. PreCheck is well marked.",
    connection: "The train to N and S satellites is airside. Budget 15 min if you have to ride it.",
    watch: "S satellite and north satellite ends look at the long-haul ramp. Rainy glass still works.",
    skyline: "Rainier is southeast — on a southbound departure it can fill the left windows on a clear day.",
    layover: {
      m45: "Stay near the gate. Satellites add a train.",
      m90: "Main terminal food is the move.",
      m180: "Don’t go downtown. The train is longer than the map.",
    },
    heavies: "AS, DL, NH, JL, KE, SQ, EK, BA, LH",
  },
  {
    icao: "KDEN",
    iata: "DEN",
    name: "Denver",
    city: "Denver",
    country: "US",
    lat: 39.8561,
    lon: -104.6737,
    tz: "America/Denver",
    elevationFt: 5434,
    oneLiner: "High, huge, and often windy. United and Frontier, with a mountain wall to the west.",
    terminals: "Jeppesen terminal plus A, B, C via train.",
    security: "Main checkpoint in Jeppesen, plus A-bridge. PreCheck is fast here more often than not.",
    connection: "B to C is a train. Same-concourse 40 min is easy; cross-concourse 55 min is the floor.",
    watch: "A gates, west-facing, catch the Front Range on a clear afternoon. Widebodies are less common than the coasts.",
    skyline: "The Front Range is west. Westbound departures put mountains off the nose, then both sides.",
    layover: {
      m45: "Stay in your concourse.",
      m90: "Ride the train only if you know the gate. Food is better in A and B.",
      m180: "The city is 40+ minutes each way. Don’t.",
    },
    heavies: "UA 787/777, occasional LH and BA.",
  },
  {
    icao: "KATL",
    iata: "ATL",
    name: "Hartsfield-Jackson",
    city: "Atlanta",
    country: "US",
    lat: 33.6407,
    lon: -84.4277,
    tz: "America/New_York",
    elevationFt: 1026,
    oneLiner: "Delta’s machine. The plane train is the airport. If you can walk a concourse, you’re already winning.",
    terminals: "Domestic T / A–D / E, plus F international.",
    security: "Main domestic checkpoint is efficient; F has its own. PreCheck is worth it in the bank.",
    connection: "Plane Train is airside A through F. 45 minutes is a normal Delta connect. F to T is still a ride.",
    watch: "E and F for heavies. Concourse F windows are the international show.",
    skyline: "Not a skyline airport. Watch the parallel runways instead — it’s the show.",
    layover: {
      m45: "Stay in concourse. The train can wait.",
      m90: "Food in A, B, or T. Don’t reclear.",
      m180: "You can walk the whole spine. The city is not worth the round trip.",
    },
    heavies: "DL 330/350/767, VS, AF, KL, KE, AM, LA",
  },
  {
    icao: "KDFW",
    iata: "DFW",
    name: "Dallas/Fort Worth",
    city: "Dallas",
    country: "US",
    lat: 32.8998,
    lon: -97.0403,
    tz: "America/Chicago",
    elevationFt: 607,
    oneLiner: "American’s mega-hub. Skylink is the airport. Everything is farther than it looks.",
    terminals: "A–E plus D international. Skylink is airside.",
    security: "Checkpoint at every terminal. D can back up on international banks.",
    connection: "Skylink connects all terminals airside. Same-terminal 40 min; cross-terminal 55–70.",
    watch: "D gates for heavies. A and C are American domestic volume.",
    skyline: "No close skyline. Big Texas sky and long taxi — the taxi is the view.",
    layover: {
      m45: "Do not Skylink unless the app says so.",
      m90: "Eat in-terminal. D and A are strongest.",
      m180: "You can change terminals in comfort. Skip downtown Dallas.",
    },
    heavies: "AA 787/777, BA, QR, EK, JL, QF, IB",
  },
  {
    icao: "KBOS",
    iata: "BOS",
    name: "Logan",
    city: "Boston",
    country: "US",
    lat: 42.3656,
    lon: -71.0096,
    tz: "America/New_York",
    elevationFt: 20,
    oneLiner: "Harbor airport. Short connections are a myth if you change terminals. The city is actually close.",
    terminals: "A (Delta), B (AA/others), C (JetBlue), E international.",
    security: "Each terminal has its own. E is the international filter.",
    connection: "A–B–C–E walks and shuttles. Terminal change on a 50-minute sit is optimistic.",
    watch: "E for heavies over the harbor. C has good JetBlue ramp glass.",
    skyline: "The city is west. On a 22 departure downtown can sit off the right after rotation.",
    layover: {
      m45: "Stay in terminal.",
      m90: "Eat airside. The harbor walk is landside.",
      m180: "The city is close enough for a real coffee in the Seaport if you have no bag. Still tight.",
    },
    heavies: "B6 Mint transcon, VS, BA, AF, EI, AY, QR, EK, TK",
  },
  {
    icao: "KMIA",
    iata: "MIA",
    name: "Miami",
    city: "Miami",
    country: "US",
    lat: 25.7959,
    lon: -80.287,
    tz: "America/New_York",
    elevationFt: 8,
    oneLiner: "American’s Latin hub. Heat, long-haul to the south, and a terminal that rewards staying put.",
    terminals: "South (D, American) and North (E–J). D is the beast.",
    security: "D checkpoint is huge. PreCheck is the difference between 10 minutes and 40.",
    connection: "D is airside with itself. North/South changes need more time than the map admits.",
    watch: "D satellite gates for heavies to São Paulo, Buenos Aires, London, Madrid.",
    skyline: "The beach is east. Eastbound departures can put water off the nose in minutes.",
    layover: {
      m45: "Stay in D.",
      m90: "Food in D is enough. Don’t go landside.",
      m180: "A beach run is a fantasy unless you live here.",
    },
    heavies: "AA 777/787, IB, BA, AF, LA, AV, JJ, QR, EK",
  },
  {
    icao: "KCLT",
    iata: "CLT",
    name: "Charlotte Douglas",
    city: "Charlotte",
    country: "US",
    lat: 35.214,
    lon: -80.9431,
    tz: "America/New_York",
    elevationFt: 748,
    oneLiner: "American’s Southeast connecting hub, with a compact terminal feeding a very busy parallel-runway operation.",
    terminals: "One terminal with concourses A–E. American dominates B, C, and D.",
    security: "Central checkpoints serve all concourses. Connection flows stay airside.",
    connection: "All concourses are walkable airside; long end-to-end walks can still take 15–20 minutes.",
    watch: "B/C/D for American banks and widebody turns. The ramp stays busy nearly all day.",
    skyline: "Uptown Charlotte is east of the field and can appear on eastbound departures and arrivals.",
    layover: { m45: "Stay in your concourse.", m90: "Walk the central atrium or eat airside.", m180: "The terminal is easier than leaving the airport." },
    heavies: "AA 777/787 seasonal and international partners",
  },
  {
    icao: "KLAS",
    iata: "LAS",
    name: "Harry Reid",
    city: "Las Vegas",
    country: "US",
    lat: 36.084,
    lon: -115.1537,
    tz: "America/Los_Angeles",
    elevationFt: 2181,
    oneLiner: "A dense desert airport beside the Strip, with parallel runways and constant high-volume leisure traffic.",
    terminals: "Terminal 1 serves A/B/C/D; Terminal 3 serves D/E and most international operations.",
    security: "Multiple checkpoints by terminal. D gates can be reached from either terminal via tram.",
    connection: "Airside trains link remote concourses; terminal-side changes can add time.",
    watch: "D and E for the best mix of long-haul and domestic traffic.",
    skyline: "The Strip sits west-northwest of the field and is often visible immediately after takeoff or on approach.",
    layover: { m45: "Stay near the gate.", m90: "Use the concourse train only if needed.", m180: "The Strip is close but airport timing can still make a city run risky." },
    heavies: "BA, VS, KE, seasonal leisure widebodies",
  },
  {
    icao: "KMCO",
    iata: "MCO",
    name: "Orlando",
    city: "Orlando",
    country: "US",
    lat: 28.4312,
    lon: -81.3081,
    tz: "America/New_York",
    elevationFt: 96,
    oneLiner: "A four-runway leisure mega-airport with satellite airsides and heavy family-travel peaks.",
    terminals: "Terminals A/B feed Airsides 1–4; Terminal C is the newer international-focused complex.",
    security: "A/B share large central checkpoints; C has its own checkpoint.",
    connection: "A/B satellites use people movers. Terminal C is separate and can require a landside transfer.",
    watch: "Airside 4 and Terminal C see much of the international widebody traffic.",
    skyline: "Orlando’s core is northwest; most views are lakes, suburbs, and theme-park sprawl.",
    layover: { m45: "Stay in your airside.", m90: "Food and services are plentiful airside.", m180: "Do not count on a theme-park or downtown run." },
    heavies: "BA, VS, LH, EK and seasonal transatlantic traffic",
  },
  {
    icao: "KPHX",
    iata: "PHX",
    name: "Phoenix Sky Harbor",
    city: "Phoenix",
    country: "US",
    lat: 33.4342,
    lon: -112.0116,
    tz: "America/Phoenix",
    elevationFt: 1135,
    oneLiner: "A compact desert hub with parallel east-west runways and strong American and Southwest operations.",
    terminals: "Terminal 3 and Terminal 4; Terminal 4 is the main American/Southwest complex.",
    security: "Separate checkpoints by terminal and concourse area.",
    connection: "Terminal 4 concourses are connected airside; T3 and T4 require landside Sky Train transfer.",
    watch: "T4 gives the best view of the dense American and Southwest banks.",
    skyline: "Downtown is west; Camelback and surrounding mountains provide the strongest visual references.",
    layover: { m45: "Stay in terminal.", m90: "T4 has enough food and room to move.", m180: "A city run is possible but usually not worth the security reset." },
    heavies: "AA widebodies, BA and seasonal long-haul",
  },
  {
    icao: "KEWR",
    iata: "EWR",
    name: "Newark Liberty",
    city: "Newark",
    country: "US",
    lat: 40.6895,
    lon: -74.1745,
    tz: "America/New_York",
    elevationFt: 18,
    oneLiner: "United’s New York-area fortress with complex taxi flows and frequent runway congestion.",
    terminals: "Terminal A, Terminal B, Terminal C. United is concentrated in C with a major presence in A.",
    security: "Each terminal has its own checkpoint. Terminal changes can require AirTrain and re-screening.",
    connection: "Same-terminal connections are straightforward; cross-terminal connections need extra time.",
    watch: "Terminal C for United widebodies; B for many foreign carriers.",
    skyline: "Manhattan is northeast and often visible on north/east departures and arrivals.",
    layover: { m45: "Stay in terminal.", m90: "Do not switch terminals unless required.", m180: "Manhattan is too risky for a short layover." },
    heavies: "UA 777/787, LH, BA, TAP, SAS and other transatlantic carriers",
  },
  {
    icao: "KIAH",
    iata: "IAH",
    name: "George Bush Intercontinental",
    city: "Houston",
    country: "US",
    lat: 29.9902,
    lon: -95.3368,
    tz: "America/Chicago",
    elevationFt: 97,
    oneLiner: "United’s Gulf hub with five terminals, long taxi distances, and a large international operation.",
    terminals: "A, B, C, D, E. C/E are major United hubs; D/E handle much international traffic.",
    security: "Multiple terminal checkpoints. Airside Skyway links all terminals.",
    connection: "Use the Skyway airside for terminal changes; walking between some concourses is lengthy.",
    watch: "D/E for international widebodies and United long-haul.",
    skyline: "Downtown Houston is south and usually distant from the field.",
    layover: { m45: "Stay near your concourse.", m90: "Use Skyway only if needed.", m180: "Remain airside; Houston is too far for a quick visit." },
    heavies: "UA 777/787, LH, BA, NH, SQ, EK, QR",
  },
  {
    icao: "KMSP",
    iata: "MSP",
    name: "Minneapolis-St. Paul",
    city: "Minneapolis",
    country: "US",
    lat: 44.8848,
    lon: -93.2223,
    tz: "America/Chicago",
    elevationFt: 841,
    oneLiner: "Delta’s Upper Midwest hub with two terminals and strong winter-weather operations.",
    terminals: "Terminal 1 Lindbergh with concourses A–G; Terminal 2 Humphrey for several low-cost carriers.",
    security: "Terminal 1 has multiple checkpoints; Terminal 2 has separate screening.",
    connection: "Most Delta connections remain in Terminal 1. Terminal changes use light rail landside.",
    watch: "G concourse and the international gates for Delta widebodies.",
    skyline: "Downtown Minneapolis is northwest of the field.",
    layover: { m45: "Stay in your concourse.", m90: "Terminal 1 is easy to explore airside.", m180: "The city is reachable by rail but still tight for a short layover." },
    heavies: "DL A330/A350, AF/KL seasonal partners",
  },
  {
    icao: "KFLL",
    iata: "FLL",
    name: "Fort Lauderdale-Hollywood",
    city: "Fort Lauderdale",
    country: "US",
    lat: 26.0726,
    lon: -80.1527,
    tz: "America/New_York",
    elevationFt: 9,
    oneLiner: "A compact South Florida airport with intense low-cost traffic and close-in coastal approaches.",
    terminals: "Terminals 1–4. Southwest is strong in T1; JetBlue and others use T3/T4.",
    security: "Each terminal has its own checkpoint; not all terminal areas connect airside.",
    connection: "Same-terminal is easiest. Cross-terminal transfers may require landside walking or shuttle.",
    watch: "T4 for international traffic; T1/T3 for dense domestic activity.",
    skyline: "The Atlantic coast is immediately east; Fort Lauderdale and beaches are visible on many approaches.",
    layover: { m45: "Stay in terminal.", m90: "Do not change terminals without a gate reason.", m180: "The beach is close but security makes a short trip risky." },
    heavies: "Occasional transatlantic and Latin America widebodies",
  },
  {
    icao: "KLGA",
    iata: "LGA",
    name: "LaGuardia",
    city: "New York",
    country: "US",
    lat: 40.7769,
    lon: -73.874,
    tz: "America/New_York",
    elevationFt: 21,
    oneLiner: "A close-in New York airport with short taxi distances, intersecting runway constraints, and spectacular city views.",
    terminals: "Terminal A, Terminal B, Terminal C. Delta is centered in C.",
    security: "Modern checkpoints in B and C; terminals are separate landside.",
    connection: "Stay within your terminal. Cross-terminal transfers need a bus or landside movement.",
    watch: "C for Delta; B for American, United, Southwest and others.",
    skyline: "Manhattan is southwest and often dominates approaches and departures.",
    layover: { m45: "Stay put.", m90: "Remain in terminal.", m180: "The city is close geographically but traffic makes a quick visit unreliable." },
    heavies: "Mostly narrowbody operations",
  },
  {
    icao: "KDTW",
    iata: "DTW",
    name: "Detroit Metropolitan",
    city: "Detroit",
    country: "US",
    lat: 42.2124,
    lon: -83.3534,
    tz: "America/Detroit",
    elevationFt: 645,
    oneLiner: "Delta’s Great Lakes hub, built around the long McNamara terminal and parallel runway system.",
    terminals: "McNamara Terminal for Delta and partners; Evans Terminal for most other airlines.",
    security: "Separate terminal checkpoints. McNamara has multiple screening locations.",
    connection: "McNamara’s tram makes long concourse connections fast; terminal changes are landside.",
    watch: "McNamara A concourse for Delta international widebodies.",
    skyline: "Downtown Detroit is northeast and usually distant from the airport.",
    layover: { m45: "Use the tram if needed.", m90: "McNamara is easy to explore.", m180: "Stay airport-side; downtown is too far for a short layover." },
    heavies: "DL A330/A350, AF and partner long-haul",
  },
  {
    icao: "KPHL",
    iata: "PHL",
    name: "Philadelphia",
    city: "Philadelphia",
    country: "US",
    lat: 39.8729,
    lon: -75.2437,
    tz: "America/New_York",
    elevationFt: 36,
    oneLiner: "American’s Northeast hub with seven connected terminals and a busy east-west runway system.",
    terminals: "A East/West, B, C, D, E, F. American dominates A–C and F.",
    security: "Multiple checkpoints; most terminals connect airside after security.",
    connection: "Most terminals are walkable airside; shuttle service helps reach F.",
    watch: "A West for international widebodies and American long-haul.",
    skyline: "Center City is northeast and can appear on departures and approaches.",
    layover: { m45: "Stay near your terminal.", m90: "Airside connections are manageable.", m180: "Center City is possible by rail but not ideal on a short connection." },
    heavies: "AA 787, BA, LH and transatlantic partners",
  },
  {
    icao: "KSLC",
    iata: "SLC",
    name: "Salt Lake City",
    city: "Salt Lake City",
    country: "US",
    lat: 40.7899,
    lon: -111.9791,
    tz: "America/Denver",
    elevationFt: 4227,
    oneLiner: "Delta’s Mountain West hub with a new linear terminal and dramatic Wasatch views.",
    terminals: "One terminal complex with concourses A and B.",
    security: "Central screening serves both concourses.",
    connection: "A and B are connected airside by a long tunnel; allow walking time.",
    watch: "A concourse for Delta mainline and long-haul operations.",
    skyline: "The Wasatch Range east of the airport is the dominant visual reference.",
    layover: { m45: "Stay on your concourse.", m90: "Allow time for the A–B walk.", m180: "Downtown is close but mountain-weather disruptions can change timing quickly." },
    heavies: "DL A330/767 and seasonal Europe service",
  },
  {
    icao: "KBWI",
    iata: "BWI",
    name: "Baltimore/Washington International",
    city: "Baltimore",
    country: "US",
    lat: 39.1754,
    lon: -76.6683,
    tz: "America/New_York",
    elevationFt: 146,
    oneLiner: "Southwest’s major Mid-Atlantic base with a compact terminal and high-frequency domestic operation.",
    terminals: "Concourses A–E in one terminal complex; Southwest dominates A/B.",
    security: "Several checkpoints feed connected concourses.",
    connection: "Most concourses are walkable airside; international arrivals in E may require reclear.",
    watch: "A/B for Southwest banks; E for international service.",
    skyline: "Baltimore is northeast; Washington is southwest and farther away.",
    layover: { m45: "Stay in concourse.", m90: "Easy airside connection airport.", m180: "Baltimore is reachable but not necessary on a short stop." },
    heavies: "BA and occasional international widebody service",
  },
  {
    icao: "KIAD",
    iata: "IAD",
    name: "Washington Dulles",
    city: "Dulles",
    country: "US",
    lat: 38.9531,
    lon: -77.4565,
    tz: "America/New_York",
    elevationFt: 313,
    oneLiner: "United’s Washington international hub with midfield concourses and long-haul traffic throughout the day.",
    terminals: "Main terminal with A/B and C/D concourses; AeroTrain serves most gates.",
    security: "Central main-terminal checkpoints. International arrivals funnel through customs facilities.",
    connection: "AeroTrain and mobile lounges connect concourses; C/D walking distances can be long.",
    watch: "B, C and D for international heavies and United long-haul.",
    skyline: "Washington is east and generally too distant for a strong skyline view from the field.",
    layover: { m45: "Stay close to your concourse.", m90: "Use AeroTrain efficiently.", m180: "Downtown Washington is too far for a short layover." },
    heavies: "UA 777/787, LH, BA, AF, EK, QR, NH, TK",
  },
  {
    icao: "KSAN",
    iata: "SAN",
    name: "San Diego",
    city: "San Diego",
    country: "US",
    lat: 32.7338,
    lon: -117.1933,
    tz: "America/Los_Angeles",
    elevationFt: 17,
    oneLiner: "A single-runway downtown airport famous for its steep-looking city approach and compact footprint.",
    terminals: "Terminal 1 and Terminal 2; Terminal 2 handles most international and long-haul service.",
    security: "Separate checkpoint areas by terminal; some concourses are not connected airside.",
    connection: "Same-terminal transfers are easy. Terminal changes may require landside movement.",
    watch: "Terminal 2 for international and long-haul aircraft.",
    skyline: "Downtown sits immediately southeast and is prominent on the classic runway 27 approach.",
    layover: { m45: "Stay in terminal.", m90: "The airport is compact and easy to navigate.", m180: "Downtown is close enough for a quick visit only with plenty of buffer." },
    heavies: "BA, LH, JL seasonal/long-haul service",
  },
  {
    icao: "EGLL",
    iata: "LHR",
    name: "Heathrow",
    city: "London",
    country: "GB",
    lat: 51.47,
    lon: -0.4543,
    tz: "Europe/London",
    elevationFt: 83,
    oneLiner: "The world’s transfer machine. Terminals are separate airports. Immigration is the real connection time.",
    terminals: "T2, T3, T4, T5 (BA). T1 is gone.",
    security: "Fast Track where you have it. T5 is smoothest for BA; T3 can be slow.",
    connection: "Same-terminal 60 min can work. Terminal change 90–120. Arriving extra-Schengen into a domestic gate is a different sport.",
    watch: "T5B/C for BA heavies. T3 for SQ, EK, VS. North runway views from T5.",
    skyline: "Central London is east. You rarely see it on departure — this is suburbs and the M25.",
    layover: {
      m45: "Impossible as a terminal change. Stay seated.",
      m90: "Same terminal only.",
      m180: "T5 is a layover destination of its own. The city wants four hours, not three.",
    },
    heavies: "BA A350/777/380, VS, SQ, EK, QF, CX, AI, UA, AA",
  },
  {
    icao: "EHAM",
    iata: "AMS",
    name: "Schiphol",
    city: "Amsterdam",
    country: "NL",
    lat: 52.3105,
    lon: 4.7683,
    tz: "Europe/Amsterdam",
    elevationFt: -11,
    oneLiner: "One terminal, below sea level, built for walking. KLM’s hub and a layover that actually works.",
    terminals: "A single complex: 1–3, lounges and piers including the F/G non-Schengen piers.",
    security: "Central security. It’s usually faster than Heathrow, slower than a US domestic hub.",
    connection: "50 minutes is a real KLM connect if you don’t change piers blindly. Non-Schengen adds passport time.",
    watch: "F/G piers for long-haul. The panoramic terrace is landside — not for a tight sit.",
    skyline: "Flat country. The show is the taxiway maze and the KLM widebody parade.",
    layover: {
      m45: "Stay in your pier.",
      m90: "Walk the main plaza. It’s the point of Schiphol.",
      m180: "The Rijksmuseum outpost and the plaza are the layover. City center wants more time.",
    },
    heavies: "KL 777/787/330, DL, SQ, KE, CZ, AV, G3",
  },
  {
    icao: "LFPG",
    iata: "CDG",
    name: "Charles de Gaulle",
    city: "Paris",
    country: "FR",
    lat: 49.0097,
    lon: 2.5479,
    tz: "Europe/Paris",
    elevationFt: 392,
    oneLiner: "Beautiful and hostile. Terminals 1, 2, 3 are different planets. Build slack into everything.",
    terminals: "T1, T2 (A–G, Air France in 2E/2F), T3.",
    security: "2E is the long-haul machine. 2F Schengen. Signage assumes you know the alphabet.",
    connection: "Same 2E hall 70 min. 2E to 2F can work. T1 to T2 is a CDGVAL ride plus security — treat it as 2 hours.",
    watch: "2E K/L/M for AF heavies and partners. The satellites are the show.",
    skyline: "You will not see Paris from the field. Sit left or right for the city on a typical easterly arrival instead.",
    layover: {
      m45: "Do not move.",
      m90: "Stay in your hall. 2E has enough.",
      m180: "A terminal change is the adventure. Paris itself wants a longer sit and no bags.",
    },
    heavies: "AF 777/350/380, DL, KE, CZ, SQ, QR, EK, AM",
  },
  {
    icao: "OMDB",
    iata: "DXB",
    name: "Dubai",
    city: "Dubai",
    country: "AE",
    lat: 25.2532,
    lon: 55.3657,
    tz: "Asia/Dubai",
    elevationFt: 62,
    oneLiner: "Emirates’ A380 factory. Night banks feel like a parade. The terminal is the destination.",
    terminals: "T1, T2, T3 (Emirates). T3 is the one you mean.",
    security: "T3 is built for volume. Still, the A380 bank can surprise you.",
    connection: "EK-to-EK in T3 is what the building is for. Other airlines in T1 are a different airport.",
    watch: "T3 concourse B/C for A380s at every other gate. This is the easiest A380 spotting on earth.",
    skyline: "The city is northwest. Night departures show the grid; day departures show desert then gulf.",
    layover: {
      m45: "You’re in an A380 boarding group. Stay close.",
      m90: "T3 is the layover.",
      m180: "T3 still. The city wants immigration, a taxi, and a plan — not a three-hour sit.",
    },
    heavies: "EK A380/777, QF, AI, and the night Gulf mix",
  },
  {
    icao: "RJTT",
    iata: "HND",
    name: "Haneda",
    city: "Tokyo",
    country: "JP",
    lat: 35.5494,
    lon: 139.7798,
    tz: "Asia/Tokyo",
    elevationFt: 21,
    oneLiner: "Close-in Tokyo. JAL and ANA heavies, bay views, and an airport that respects the clock.",
    terminals: "T1 JAL, T2 ANA, T3 international.",
    security: "Fast if you are on time. International T3 is its own flow.",
    connection: "Domestic T1/T2 are efficient. International to domestic is a reclear — budget real time.",
    watch: "T3 and the observation decks (landside) are legendary. Airside T2/T3 glass still catches 787s all day.",
    skyline: "The city is north. On a 34 departure you can get a Tokyo night grid off the right.",
    layover: {
      m45: "Stay in terminal. Japan runs on time — so should you.",
      m90: "Eat well airside. It’s part of the trip.",
      m180: "The city is close, immigration is the tax. Only go if you already know the train.",
    },
    heavies: "JL, NH 787/777/380, UA, DL, AA, SQ, CX, EK",
  },
  {
    icao: "PHNL",
    iata: "HNL",
    name: "Honolulu",
    city: "Honolulu",
    country: "US",
    lat: 21.3187,
    lon: -157.9225,
    tz: "Pacific/Honolulu",
    elevationFt: 13,
    oneLiner: "United and Hawaiian’s Pacific gate. Trade winds, reef on arrival, and a long walk to everywhere.",
    terminals: "Terminal 1 Hawaiian, Terminal 2 United and others, interisland.",
    security: "TSA is the bottleneck more than the walk. Interisland is a different flow.",
    connection: "Same terminal is fine. Interisland to mainland is a reclear and a shuttle — budget it.",
    watch: "T2 widebodies on the mainland banks. Reef Runway arrivals are the postcard.",
    skyline: "Waikiki and Diamond Head sit southeast. On a typical 8 arrival you get the shore off the right.",
    layover: {
      m45: "Stay airside. The walk is the layover.",
      m90: "Eat. Don’t try the city.",
      m180: "Waikiki is close if you’re already through. Bags and a taxi eat the clock.",
    },
    heavies: "UA 777/78X, HA A330/787, JL, NH, KE, QF, NZ",
  },
];

export const AIRPORT_BY_ICAO: Record<string, Airport> = Object.fromEntries(
  AIRPORTS.map((a) => [a.icao, a]),
);

export const DEFAULT_ICAO = "KORD";

export const AIRPORT_BY_IATA: Record<string, Airport> = Object.fromEntries(
  AIRPORTS.map((a) => [a.iata, a]),
);

export function airportByIata(iata: string): Airport | undefined {
  return AIRPORT_BY_IATA[iata.toUpperCase()];
}

export function airportByIcao(icao: string): Airport | undefined {
  return AIRPORT_BY_ICAO[icao.toUpperCase()];
}
