export type Layover = {
  m45: string;
  m90: string;
  m180: string;
};

export type Airport = {
  icao: string;
  iata: string;
  name: string;
  city: string;
  country: string;
  lat: number;
  lon: number;
  tz: string;
  elevationFt: number;
  oneLiner: string;
  terminals: string;
  security: string;
  connection: string;
  watch: string;
  skyline: string;
  layover: Layover;
  heavies: string;
};

export const AIRPORTS: Airport[] = [
  {
    icao: "KORD",
    iata: "ORD",
    name: "O'Hare",
    city: "Chicago",
    country: "US",
    lat: 41.9786,
    lon: -87.9048,
    tz: "America/Chicago",
    elevationFt: 672,
    oneLiner: "United’s fortress, American’s other hub, and the best widebody mix in the Midwest.",
    terminals: "T1 United, T2 mixed, T3 American, T5 international.",
    security: "PreCheck in every terminal. International arrivals land in T5 and reclear customs there.",
    connection: "T1–T2–T3 are airside. T5 is not — budget 25–40 min plus the ATS or a reclear if you arrive internationally.",
    watch: "T5 food court and gate windows face the international ramp. T1 rotunda looks over United’s widebody gates. Heavies: BA, LH, JL, NH, EK, QR, TK, LX.",
    skyline: "Downtown sits southeast of the field. Eastbound departures often put the skyline off the right; southbound, off the left.",
    layover: {
      m45: "Stay in your departure terminal. Don’t change buildings.",
      m90: "Eat in-terminal. T3 and T1 have the most options. Skip the city.",
      m180: "T1–T3 are walkable airside. A city run is only realistic if you have bags-in-hold and three hours plus, and even then it’s tight.",
    },
    heavies: "BA, LH, LX, OS, SK, QR, EK, TK, NH, JL, EY, SQ",
  },
  {
    icao: "KMDW",
    iata: "MDW",
    name: "Midway",
    city: "Chicago",
    country: "US",
    lat: 41.7868,
    lon: -87.7522,
    tz: "America/Chicago",
    elevationFt: 620,
    oneLiner: "Close-in Southwest field. Short runways, loud departures, downtown on a short final.",
    terminals: "One main terminal, three concourses A–C.",
    security: "A single checkpoint. PreCheck is there but the line is the line — Midway is compact.",
    connection: "Everything is one building. A 35-minute connection is normal here.",
    watch: "Concourse A windows look over the south ramp. Nothing widebody — this is 737 country.",
    skyline: "Arrivals from the east can run the lakefront. Sit on the right on a typical 31C final for downtown.",
    layover: {
      m45: "You’re already at the gate. Grab food in the food court past security.",
      m90: "Stay airside. The city is close in miles, not in time.",
      m180: "You can make a neighborhood meal in Bridgeport or Pilsen if you have no checked bag. Tight.",
    },
    heavies: "Rare. Occasional diversion widebodies.",
  },
  {
    icao: "KJFK",
    iata: "JFK",
    name: "Kennedy",
    city: "New York",
    country: "US",
    lat: 40.6413,
    lon: -73.7781,
    tz: "America/New_York",
    elevationFt: 13,
    oneLiner: "The US international gateway. Terminals are separate worlds — treat a terminal change as a new airport.",
    terminals: "T1, T4, T5 (JetBlue), T7, T8 (American). T2 is gone.",
    security: "Each terminal has its own checkpoint. AirTrain is landside. PreCheck availability varies by terminal.",
    connection: "Different terminals usually means AirTrain + re-security. Self-connects under 2 hours are a gamble.",
    watch: "T4 terrace-facing gates catch heavies. T5 has good ramp glass. T8 for AA long-haul.",
    skyline: "Manhattan is west-northwest. On a 31L departure you often see it off the right after the turn.",
    layover: {
      m45: "Do not change terminals.",
      m90: "Stay inside your terminal. T4 and T5 have enough food to survive.",
      m180: "A terminal change is possible. A city run is not, unless you like watching the clock the whole time.",
    },
    heavies: "EK, QR, EY, BA, VS, AF, DL, AA, SQ, EK, KE, NH, JL",
  },
  {
    icao: "KLAX",
    iata: "LAX",
    name: "Los Angeles",
    city: "Los Angeles",
    country: "US",
    lat: 33.9416,
    lon: -118.4085,
    tz: "America/Los_Angeles",
    elevationFt: 128,
    oneLiner: "West-coast long-haul factory. Ocean departures, Tom Bradley heavies, and a horseshoe that takes longer than it looks.",
    terminals: "TBIT (TBIT/T3/T4/T5/T6/T7/T8) plus T1. TBIT is the international core.",
    security: "PreCheck in most terminals. TBIT can be slow in the evening bank.",
    connection: "The north and south complexes are connected airside via tunnels and the new walkways — still budget 20–30 min of walking.",
    watch: "TBIT gates for A380s and Gulf heavies. Inboard TBIT windows look at the Bradley alley.",
    skyline: "Ocean is west. On a 25 departure you see water off the nose; downtown is east, often behind you.",
    layover: {
      m45: "Stay put. The horseshoe eats time.",
      m90: "Eat in your terminal. TBIT has the best airside food.",
      m180: "You can walk TBIT to T4/T5. The city is a trap on a three-hour sit.",
    },
    heavies: "SQ, NH, JL, KE, QF, EK, QR, BA, AF, NZ, VA",
  },
  {
    icao: "KSFO",
    iata: "SFO",
    name: "San Francisco",
    city: "San Francisco",
    country: "US",
    lat: 37.6213,
    lon: -122.379,
    tz: "America/Los_Angeles",
    elevationFt: 13,
    oneLiner: "Fog, long-haul, and a bay that makes every approach a view. United’s west hub.",
    terminals: "T1, T2, T3 (United), International G.",
    security: "PreCheck in every terminal. International G has its own checkpoint.",
    connection: "Domestic terminals are airside-linked. G to domestic can require a walk plus possible reclear on arrival.",
    watch: "G gates for heavies over the bay. T3 also sees United 787s and 777s.",
    skyline: "The city and bridge sit north of the field. On a 28 departure the bay is off the right almost immediately.",
    layover: {
      m45: "Stay in terminal.",
      m90: "Airside food is fine. Don’t leave security.",
      m180: "BART to the city is possible with no bag, but 90 minutes downtown is the real budget — most people overstay.",
    },
    heavies: "UA, SQ, NH, JL, EK, BA, LH, AF, QF, NZ, PR",
  },
  {
    icao: "KSEA",
    iata: "SEA",
    name: "Sea-Tac",
    city: "Seattle",
    country: "US",
    lat: 47.4502,
    lon: -122.3088,
    tz: "America/Los_Angeles",
    elevationFt: 433,
    oneLiner: "Alaska’s home and a widebody launchpad to Asia. Rain, volcanoes, and a single long terminal.",
    terminals: "One main terminal, A–D plus N and S satellites.",
    security: "A central checkpoint plus satellite checkpoints. PreCheck is well marked.",
    connection: "The train to N and S satellites is airside. Budget 15 min if you have to ride it.",
    watch: "S satellite and north satellite ends look at the long-haul ramp. Rainy glass still works.",
    skyline: "Rainier is southeast — on a southbound departure it can fill the left windows on a clear day.",
    layover: {
      m45: "Stay near the gate. Satellites add a train.",
      m90: "Main terminal food is the move.",
      m180: "Don’t go downtown. The train is longer than the map.",
    },
    heavies: "AS, DL, NH, JL, KE, SQ, EK, BA, LH",
  },
  {
    icao: "KDEN",
    iata: "DEN",
    name: "Denver",
    city: "Denver",
    country: "US",
    lat: 39.8561,
    lon: -104.6737,
    tz: "America/Denver",
    elevationFt: 5434,
    oneLiner: "High, huge, and often windy. United and Frontier, with a mountain wall to the west.",
    terminals: "Jeppesen terminal plus A, B, C via train.",
    security: "Main checkpoint in Jeppesen, plus A-bridge. PreCheck is fast here more often than not.",
    connection: "B to C is a train. Same-concourse 40 min is easy; cross-concourse 55 min is the floor.",
    watch: "A gates, west-facing, catch the Front Range on a clear afternoon. Widebodies are less common than the coasts.",
    skyline: "The Front Range is west. Westbound departures put mountains off the nose, then both sides.",
    layover: {
      m45: "Stay in your concourse.",
      m90: "Ride the train only if you know the gate. Food is better in A and B.",
      m180: "The city is 40+ minutes each way. Don’t.",
    },
    heavies: "UA 787/777, occasional LH and BA.",
  },
  {
    icao: "KATL",
    iata: "ATL",
    name: "Hartsfield-Jackson",
    city: "Atlanta",
    country: "US",
    lat: 33.6407,
    lon: -84.4277,
    tz: "America/New_York",
    elevationFt: 1026,
    oneLiner: "Delta’s machine. The plane train is the airport. If you can walk a concourse, you’re already winning.",
    terminals: "Domestic T / A–D / E, plus F international.",
    security: "Main domestic checkpoint is efficient; F has its own. PreCheck is worth it in the bank.",
    connection: "Plane Train is airside A through F. 45 minutes is a normal Delta connect. F to T is still a ride.",
    watch: "E and F for heavies. Concourse F windows are the international show.",
    skyline: "Not a skyline airport. Watch the parallel runways instead — it’s the show.",
    layover: {
      m45: "Stay in concourse. The train can wait.",
      m90: "Food in A, B, or T. Don’t reclear.",
      m180: "You can walk the whole spine. The city is not worth the round trip.",
    },
    heavies: "DL 330/350/767, VS, AF, KL, KE, AM, LA",
  },
  {
    icao: "KDFW",
    iata: "DFW",
    name: "Dallas/Fort Worth",
    city: "Dallas",
    country: "US",
    lat: 32.8998,
    lon: -97.0403,
    tz: "America/Chicago",
    elevationFt: 607,
    oneLiner: "American’s mega-hub. Skylink is the airport. Everything is farther than it looks.",
    terminals: "A–E plus D international. Skylink is airside.",
    security: "Checkpoint at every terminal. D can back up on international banks.",
    connection: "Skylink connects all terminals airside. Same-terminal 40 min; cross-terminal 55–70.",
    watch: "D gates for heavies. A and C are American domestic volume.",
    skyline: "No close skyline. Big Texas sky and long taxi — the taxi is the view.",
    layover: {
      m45: "Do not Skylink unless the app says so.",
      m90: "Eat in-terminal. D and A are strongest.",
      m180: "You can change terminals in comfort. Skip downtown Dallas.",
    },
    heavies: "AA 787/777, BA, QR, EK, JL, QF, IB",
  },
  {
    icao: "KBOS",
    iata: "BOS",
    name: "Logan",
    city: "Boston",
    country: "US",
    lat: 42.3656,
    lon: -71.0096,
    tz: "America/New_York",
    elevationFt: 20,
    oneLiner: "Harbor airport. Short connections are a myth if you change terminals. The city is actually close.",
    terminals: "A (Delta), B (AA/others), C (JetBlue), E international.",
    security: "Each terminal has its own. E is the international filter.",
    connection: "A–B–C–E walks and shuttles. Terminal change on a 50-minute sit is optimistic.",
    watch: "E for heavies over the harbor. C has good JetBlue ramp glass.",
    skyline: "The city is west. On a 22 departure downtown can sit off the right after rotation.",
    layover: {
      m45: "Stay in terminal.",
      m90: "Eat airside. The harbor walk is landside.",
      m180: "The city is close enough for a real coffee in the Seaport if you have no bag. Still tight.",
    },
    heavies: "B6 Mint transcon, VS, BA, AF, EI, AY, QR, EK, TK",
  },
  {
    icao: "KMIA",
    iata: "MIA",
    name: "Miami",
    city: "Miami",
    country: "US",
    lat: 25.7959,
    lon: -80.287,
    tz: "America/New_York",
    elevationFt: 8,
    oneLiner: "American’s Latin hub. Heat, long-haul to the south, and a terminal that rewards staying put.",
    terminals: "South (D, American) and North (E–J). D is the beast.",
    security: "D checkpoint is huge. PreCheck is the difference between 10 minutes and 40.",
    connection: "D is airside with itself. North/South changes need more time than the map admits.",
    watch: "D satellite gates for heavies to São Paulo, Buenos Aires, London, Madrid.",
    skyline: "The beach is east. Eastbound departures can put water off the nose in minutes.",
    layover: {
      m45: "Stay in D.",
      m90: "Food in D is enough. Don’t go landside.",
      m180: "A beach run is a fantasy unless you live here.",
    },
    heavies: "AA 777/787, IB, BA, AF, LA, AV, JJ, QR, EK",
  },
  {
    icao: "EGLL",
    iata: "LHR",
    name: "Heathrow",
    city: "London",
    country: "GB",
    lat: 51.47,
    lon: -0.4543,
    tz: "Europe/London",
    elevationFt: 83,
    oneLiner: "The world’s transfer machine. Terminals are separate airports. Immigration is the real connection time.",
    terminals: "T2, T3, T4, T5 (BA). T1 is gone.",
    security: "Fast Track where you have it. T5 is smoothest for BA; T3 can be slow.",
    connection: "Same-terminal 60 min can work. Terminal change 90–120. Arriving extra-Schengen into a domestic gate is a different sport.",
    watch: "T5B/C for BA heavies. T3 for SQ, EK, VS. North runway views from T5.",
    skyline: "Central London is east. You rarely see it on departure — this is suburbs and the M25.",
    layover: {
      m45: "Impossible as a terminal change. Stay seated.",
      m90: "Same terminal only.",
      m180: "T5 is a layover destination of its own. The city wants four hours, not three.",
    },
    heavies: "BA A350/777/380, VS, SQ, EK, QF, CX, AI, UA, AA",
  },
  {
    icao: "EHAM",
    iata: "AMS",
    name: "Schiphol",
    city: "Amsterdam",
    country: "NL",
    lat: 52.3105,
    lon: 4.7683,
    tz: "Europe/Amsterdam",
    elevationFt: -11,
    oneLiner: "One terminal, below sea level, built for walking. KLM’s hub and a layover that actually works.",
    terminals: "A single complex: 1–3, lounges and piers including the F/G non-Schengen piers.",
    security: "Central security. It’s usually faster than Heathrow, slower than a US domestic hub.",
    connection: "50 minutes is a real KLM connect if you don’t change piers blindly. Non-Schengen adds passport time.",
    watch: "F/G piers for long-haul. The panoramic terrace is landside — not for a tight sit.",
    skyline: "Flat country. The show is the taxiway maze and the KLM widebody parade.",
    layover: {
      m45: "Stay in your pier.",
      m90: "Walk the main plaza. It’s the point of Schiphol.",
      m180: "The Rijksmuseum outpost and the plaza are the layover. City center wants more time.",
    },
    heavies: "KL 777/787/330, DL, SQ, KE, CZ, AV, G3",
  },
  {
    icao: "LFPG",
    iata: "CDG",
    name: "Charles de Gaulle",
    city: "Paris",
    country: "FR",
    lat: 49.0097,
    lon: 2.5479,
    tz: "Europe/Paris",
    elevationFt: 392,
    oneLiner: "Beautiful and hostile. Terminals 1, 2, 3 are different planets. Build slack into everything.",
    terminals: "T1, T2 (A–G, Air France in 2E/2F), T3.",
    security: "2E is the long-haul machine. 2F Schengen. Signage assumes you know the alphabet.",
    connection: "Same 2E hall 70 min. 2E to 2F can work. T1 to T2 is a CDGVAL ride plus security — treat it as 2 hours.",
    watch: "2E K/L/M for AF heavies and partners. The satellites are the show.",
    skyline: "You will not see Paris from the field. Sit left or right for the city on a typical easterly arrival instead.",
    layover: {
      m45: "Do not move.",
      m90: "Stay in your hall. 2E has enough.",
      m180: "A terminal change is the adventure. Paris itself wants a longer sit and no bags.",
    },
    heavies: "AF 777/350/380, DL, KE, CZ, SQ, QR, EK, AM",
  },
  {
    icao: "OMDB",
    iata: "DXB",
    name: "Dubai",
    city: "Dubai",
    country: "AE",
    lat: 25.2532,
    lon: 55.3657,
    tz: "Asia/Dubai",
    elevationFt: 62,
    oneLiner: "Emirates’ A380 factory. Night banks feel like a parade. The terminal is the destination.",
    terminals: "T1, T2, T3 (Emirates). T3 is the one you mean.",
    security: "T3 is built for volume. Still, the A380 bank can surprise you.",
    connection: "EK-to-EK in T3 is what the building is for. Other airlines in T1 are a different airport.",
    watch: "T3 concourse B/C for A380s at every other gate. This is the easiest A380 spotting on earth.",
    skyline: "The city is northwest. Night departures show the grid; day departures show desert then gulf.",
    layover: {
      m45: "You’re in an A380 boarding group. Stay close.",
      m90: "T3 is the layover.",
      m180: "T3 still. The city wants immigration, a taxi, and a plan — not a three-hour sit.",
    },
    heavies: "EK A380/777, QF, AI, and the night Gulf mix",
  },
  {
    icao: "RJTT",
    iata: "HND",
    name: "Haneda",
    city: "Tokyo",
    country: "JP",
    lat: 35.5494,
    lon: 139.7798,
    tz: "Asia/Tokyo",
    elevationFt: 21,
    oneLiner: "Close-in Tokyo. JAL and ANA heavies, bay views, and an airport that respects the clock.",
    terminals: "T1 JAL, T2 ANA, T3 international.",
    security: "Fast if you are on time. International T3 is its own flow.",
    connection: "Domestic T1/T2 are efficient. International to domestic is a reclear — budget real time.",
    watch: "T3 and the observation decks (landside) are legendary. Airside T2/T3 glass still catches 787s all day.",
    skyline: "The city is north. On a 34 departure you can get a Tokyo night grid off the right.",
    layover: {
      m45: "Stay in terminal. Japan runs on time — so should you.",
      m90: "Eat well airside. It’s part of the trip.",
      m180: "The city is close, immigration is the tax. Only go if you already know the train.",
    },
    heavies: "JL, NH 787/777/380, UA, DL, AA, SQ, CX, EK",
  },
  {
    icao: "PHNL",
    iata: "HNL",
    name: "Honolulu",
    city: "Honolulu",
    country: "US",
    lat: 21.3187,
    lon: -157.9225,
    tz: "Pacific/Honolulu",
    elevationFt: 13,
    oneLiner: "United and Hawaiian’s Pacific gate. Trade winds, reef on arrival, and a long walk to everywhere.",
    terminals: "Terminal 1 Hawaiian, Terminal 2 United and others, interisland.",
    security: "TSA is the bottleneck more than the walk. Interisland is a different flow.",
    connection: "Same terminal is fine. Interisland to mainland is a reclear and a shuttle — budget it.",
    watch: "T2 widebodies on the mainland banks. Reef Runway arrivals are the postcard.",
    skyline: "Waikiki and Diamond Head sit southeast. On a typical 8 arrival you get the shore off the right.",
    layover: {
      m45: "Stay airside. The walk is the layover.",
      m90: "Eat. Don’t try the city.",
      m180: "Waikiki is close if you’re already through. Bags and a taxi eat the clock.",
    },
    heavies: "UA 777/78X, HA A330/787, JL, NH, KE, QF, NZ",
  },
];

export const AIRPORT_BY_ICAO: Record<string, Airport> = Object.fromEntries(
  AIRPORTS.map((a) => [a.icao, a]),
);

export const DEFAULT_ICAO = "KORD";

export const AIRPORT_BY_IATA: Record<string, Airport> = Object.fromEntries(
  AIRPORTS.map((a) => [a.iata, a]),
);

export function airportByIata(iata: string): Airport | undefined {
  return AIRPORT_BY_IATA[iata.toUpperCase()];
}

export function airportByIcao(icao: string): Airport | undefined {
  return AIRPORT_BY_ICAO[icao.toUpperCase()];
}
